### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by mthenw** [comment]
Is there a way to exclude some files/packages? Most of the Quick wins are from mock package which is generated.

**Comment by korzonek** [comment]
@mthenw yes, you can use `.codebeatignore` file to exclude some files. Please check https://help.codebeat.co/docs/path-exclusions to learn how to do it.

**Comment by tj** [comment]
I guess the go-bindata stuff is a false negative as well, and our ./docs get an F :( hahaha

**Comment by mthenw** [comment]
Closing for now. I will add this when I will have time to configure ignored files.

**Pull request closed without merging**
