### PR TITLE
fix symlink support. Closes #401 #288

### LINKED ISSUE #401: Fix symlink support
With a simple `npm link` I get:

```
   ⨯ Error: function foo: Only regular files supported: node_modules/test
```

I thinkkkk the bulk of our logic in Function.Build for symlinks could be in utils.LoadFiles, since we'll need to read/walk directories, might as well resolve everything right there. Too tired to look into it tonight but maybe tomorrow

### PR DESCRIPTION
**Pull request by mthenw**
Important thing is that `AddDir` doesn't follow symlinks (the same reason as for `filepath.Walk`) so if there are nested symlinks it want work. Not sure it's OK(?)

### CODE REVIEW

**Comment by tj** [comment]
sounds good to me, I haven't seen many people symlink within a node module much if ever

**Comment by tobyjoe** [comment]
Having just touched this code last week, it looks good. Especially fond of the comment mentioning the symlink (potential) gotcha. If someone hits it in the future, it should be easy to find the spot to patch it.

**Comment by tj** [comment]
LGTM as well, haven't tested yet but I'll do some QA stuff before release for a quick sanity check

**Comment by tj** [comment]
awesome, works like a charm! <3

Node people can rejoice that `npm link` works haha

**Pull request merged**
