### PR TITLE
Clojure support

### PR DESCRIPTION
**Pull request by Liath**
Is basically the same as the Java plugin but with some pretty standard hook values and automagic source stripping to prevent clojure from recompiling sources.

### CODE REVIEW

**Comment by tj** [comment]
awesome :D – mind adding a hello world style _example? I've never used clojure but it would be good to test it out and we can use that for QA later

**Comment by Liath** [comment]
Added an example and fixed a mistake I made, fun stuff.

**Comment by tj** [comment]
Almost got it working :D

```
/aws/lambda/lamb_say java.lang.NullPointerException: java.lang.NullPointerException
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at clojure.string$replace.invokeStatic(string.clj:104)
	at clojure.string$replace.invoke(string.clj:75)
	at org.example.lambsay$it_says.invokeStatic(lambsay.clj:25)
	at org.example.lambsay$it_says.invoke(lambsay.clj:9)
	at org.example.lambsay$_handleRequest.invokeStatic(lambsay.clj:32)
	at org.example.lambsay$_handleRequest.invoke(lambsay.clj:27)
	at org.example.lambsay.handleRequest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by tj** [comment]
nvm works fine with the input

**Pull request merged**
