### PR TITLE
refactor metrics; add multiple functions metrics. Closes #182

### LINKED ISSUE #182: Multi-function metrics command
Nice to have consistency across all these commands. Change output to look similar to `apex list`.

### PR DESCRIPTION
**Pull request by mthenw**

### CODE REVIEW

**Comment by tj** [comment]
niceee, does this output metrics for each? looks like it aggregates them all into one. I think outputting the metrics per-function would be most useful (similar to the `list` output), since you'd usually want to see if any functions are problematic and hitting throttling etc

**Comment by mthenw** [comment]
make sense, fix in a moment

**Comment by mthenw** [comment]
@tj done

**Comment by tj** [comment]
:DDD

**Pull request merged**
