### PR TITLE
add initial --dry-run implementation. Closes #47

### LINKED ISSUE #47: Add --dry-run
Maybe. It would probably be cleanest to just swap out the lambda service with a dummy for some operations.

### PR DESCRIPTION
**Pull request by tj**
Need to play with output some more, not happy with it, and finish the inline TODOs. Currently looks like:
screen shot 2016-01-12 at 3 40 06 pm

### CODE REVIEW

**Comment by mthenw** [comment]
awesome!

**Comment by tj** [comment]
new look. might lock concurrency later so they're in order, that would be a bit easier to read

screen shot 2016-01-13 at 10 20 03 am

**Comment by tj** [comment]
k ready for review!

**Comment by mthenw** [comment]
LGTM!

**Pull request merged**
