### PR TITLE
doc(circleci): implements CD using cirleci

### PR DESCRIPTION
**Pull request by mastilver**
you can see it working there: https://circleci.com/gh/mastilver/test-apex-cd-circle/10

### CODE REVIEW

**Comment by tj** [comment]
LGTM! I wouldn't mind leaving only one function so it's not as bulky as the others, since this one is just to show circle

**Comment by mastilver** [comment]
:+1: sure doing it right now

**Comment by mastilver** [comment]
done

**Comment by tj** [comment]
awesome thanks!

**Pull request merged**
