### PR TITLE
add multiple regions and Lambda Edge support

### PR DESCRIPTION
**Pull request by tilfin**
### features
- function.json supports `edge` field to deploy `us-east-1` forcely and drop environments for Lambda@Edge (#792)
- function.json supports `region` field to deploy on different region

In order to support Lambda@Edge firstly, it was necessary to switch the AWS client for each functions.
So I changed Project.Service to the service Provider mechanism and added multiple region support.

### CODE REVIEW

**Comment by marcelpanse** [comment]
Will this be merged? I need this as well for my project.

@tilfin is there a way to use your PR in the meanwhile? (how do I install from GH?)

**Comment by tilfin** [comment]
@marcelpanse Yes! https://github.com/tilfin/apex/releases/tag/pr-824

**Comment by marcelpanse** [comment]
Works like a charm!

**Comment by JoshiiSinfield** [comment]
+1 I've now hit the multiple functions in different regions issue...

**Comment by hsienchiaolee** [comment]
+1

**Comment by billycrid** [comment]
+1

**Comment by atistler** [comment]
+1

**Comment by voigt** [comment]
@tj Any chances to get this merged/released as a new RC?

Currently working with an Apex build of this branch without any issues so far. Happy to help out if you need any specific testing.

**Comment by tj** [comment]
#904 is a bit of a blocker now :'( — haven't had time to look into it but I had to revert the last RC

**Pull request merged**
