### PR TITLE
fix type error

### PR DESCRIPTION
**Pull request by davyzhang**
Before sending a pull-request please open an issue to discuss new features or non-trivial changes.

Thanks for your contribution!

### CODE REVIEW

**Comment by polds** [comment]
That looks like it would have been panicking. Have you been seeing panics?

**Comment by davyzhang** [comment]
Nope, it won't compile at all

**Comment by davyzhang** [comment]
```go install github.com/davyzhang/apex/cmd/apex
# github.com/apex/apex/upgrade
../Dropbox/go/src/github.com/apex/apex/upgrade/upgrade.go:38: cannot use latest (type github.RepositoryRelease) as type *github.RepositoryRelease in argument to findAsset
```

So I quick fix this error, for now I can see no errors, I have used it to deploy my golang functions

**Comment by tj** [comment]
haha will vendor some day...

**Comment by mooyoul** [comment]
It seems your  `go-github` is out-of-date version. Please update go-github package by using `go get` with `-u` flag.

and Please see #465 PR, #463 issue. 
(They made breaking changes on their API. and we updated our code for following that behavior)

**Comment by davyzhang** [comment]
Sorry guys, I didn't take a deep look about this issue, I thought it maybe be a easy fixing 😄 , closing this pr now

**Pull request closed without merging**
