### PR TITLE
Drop twitter link and apex ping badge. Closes #556

### LINKED ISSUE #556: Twitter account doesn't exist
Documentation bug, there are links everywhere to @apexserverless on twitter, but it doesn't exist.

### PR DESCRIPTION
**Pull request by lc0**
Before sending a pull-request please open an issue to discuss new features or non-trivial changes.

Thanks for your contribution!

### CODE REVIEW

**Comment by tj** [comment]
heyyy don't get rid of my badge! Nice to at least have some sort of positive for spending tons of time on OSS

**Comment by tj** [comment]
623a9e7

**Comment by lc0** [comment]
haha, it was broken :) 
that's why i had an idea to remove it temporary. Or we need a proper svg there.

**Comment by tj** [comment]
my bad haha, should be fixed now, I was just seeing a cached version

**Pull request closed without merging**
