### PR TITLE
Add metric price

### PR DESCRIPTION
**Pull request by tj**
adds Lambda's cost output to `metrics`, pretty handy

screen shot 2016-04-16 at 5 00 57 pm

### CODE REVIEW

**Comment by mthenw** [comment]
Wow that's awesome.

**Comment by mthenw** [comment]
Not sure about that but aren't those prices only for US regions? What about other regions?

**Comment by tj** [comment]
hmm good question, I don't see any per-region pricing, might be ok

**Comment by tj** [comment]
<3 that squash button

**Pull request merged**
