### PR TITLE
add start of repl

### PR DESCRIPTION
**Pull request by tj**
re #250 . Need to finish a few things:

- [ ] decide on a name
- [ ] decide if we want to support non-interactive commands as well
- [ ] move to ./repl package
- [ ] change log level to warn
- [ ] add documentation / feature list item

### CODE REVIEW

**Comment by tj** [comment]
screen shot 2016-02-15 at 3 31 40 pm

**Comment by wolfeidau** [comment]
Should the prompt be apex, as apposed to lambda?

What sorts of tasks will the REPL add? Is it just to enable sharing of state between commands?

**Comment by tj** [comment]
Ah it's actually executing commands _in_ a Lambda function, so I think "lambda> " or similar would be good. The primary use-case is to debug AWS roles and inspect the lambda container (check environment variables available etc).

The use-case might not strong enough to have in core. The only way I could see it working for core is if we injected the ability to run commands in _any_ deployed function, so you can inspect local state etc haha, but that's a little weird too. I'd be happy to move it to another repo

**Comment by mthenw** [comment]
I'm also not sure about having it in core :) For starting container purpose `invoke` is fine. Other stuff like debugging/testing can be done inside function IMHO.

**Comment by tj** [comment]
Yea I think I'll move it to apex-shell, thanks guys!

**Pull request closed without merging**
