### PR TITLE
Not ignoring dirs

### PR DESCRIPTION
**Pull request by plukevdh**
Failing test case for .apexignore where directories are not ignored properly.

### CODE REVIEW

**Comment by plukevdh** [comment]
Not exactly sure how we want to solve this, but right now, I can't add a `src` dir (or similar) to a function root and then exclude it after building the src into the root function dir.

**Comment by mthenw** [comment]
you can ignore dir with `src/*`

**Comment by plukevdh** [comment]
Hum... that wasn't working before. Appears to now? Closing, thanks.

**Comment by tj** [comment]
hmm `src` should work too if we're matching .gitignore's style, I use that all the time

**Comment by mthenw** [comment]
@tj I'm pretty sure that `src` won't work as we use shell matching patterns

**Comment by tj** [comment]
maybe git does prefix matches or something, because filepath.Match fails to match `src/foo/bar` with `src/*` as well

**Pull request closed without merging**
