### PR TITLE
add IntelliJ files and binaries to the .gitignore

### PR DESCRIPTION
**Pull request by tobyjoe**
To prevent accidental commits (and local git noise) of distribution
binaries and IntelliJ IDEA project/workspace files, I added a few
patterns to the .gitignore file.

### CODE REVIEW

**Comment by mthenw** [comment]
I highly recommend adding this to your global .gitignore https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by mthenw** [comment]
BTW when developing locally you don't need to build apex. You can just run `go install ./...` and you won't have all those binaries.

**Comment by tobyjoe** [comment]
@mthenw you're totally correct - I need to get my host machine global gitignore working in the little Docker build containers I've been using lately (for a local CI sort of pattern - also why it's running ```make``` instead of ```go install```

I think that makes more sense than adding this noise to the project ```.gitignore``` - I'll kill this one.

**Comment by mthenw** [comment]
:+1:

**Pull request closed without merging**
