### PR TITLE
Fix install.sh script

### PR DESCRIPTION
**Pull request by elizar**
- remove trailing `zipball_url` and `tarball_url` from $LATEST var

### CODE REVIEW

**Comment by tj** [comment]
hmm LATEST always seems fine to me, you're getting other output?

**Comment by elizar** [comment]
@tj I'm getting this error `/usr/local/bin/apex: line 1: {error:Not Found}: command not found`.

**Comment by tj** [comment]
Ah I see.. interesting. You must be hitting the API rate limit or something? Maybe we should move the `curl` out of the pipeline and check the exit status

**Comment by elizar** [comment]
The script tries to curl the following URL which I think is not valid.

https://github.com/apex/apex/releases/download/v0.7.2zipball_url/apex_darwin_amd64

**Comment by tj** [comment]
That's not what I get:

```
$ curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2
v0.7.2
```

**Comment by elizar** [comment]
I'm getting this:
```
$ curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2
v0.7.2zipball_url
```

hmm...

**Comment by mthenw** [comment]
@elizar could you paste what you get with `curl -s https://api.github.com/repos/apex/apex/tags`

**Comment by fibo** [comment]
This should already be fixed, maybe you are using and older version of install.sh, the one in the master branch sh Io uld display an error if the curl command + grep + sed goes wrong.
Check the last lines of install.sh

**Comment by elizar** [comment]
@mthenw 

```
[{"name":"v0.7.2","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.7.2","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.7.2","commit":{"sha":"96c66ef9da1cf99c39cb1947ed2bb5f567b4db79","url":"https://api.github.com/repos/apex/apex/commits/96c66ef9da1cf99c39cb1947ed2bb5f567b4db79"}},{"name":"v0.7.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.7.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.7.1","commit":{"sha":"315cdeaee9ae93f83353c9f2b3e9c94e93086833","url":"https://api.github.com/repos/apex/apex/commits/315cdeaee9ae93f83353c9f2b3e9c94e93086833"}},{"name":"v0.7.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.7.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.7.0","commit":{"sha":"324bdcb78ca0709186f9d3013645d76f5c0f4a58","url":"https://api.github.com/repos/apex/apex/commits/324bdcb78ca0709186f9d3013645d76f5c0f4a58"}},{"name":"v0.6.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.6.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.6.1","commit":{"sha":"598a0481c9bf1ae9767623c55251488d297c3f90","url":"https://api.github.com/repos/apex/apex/commits/598a0481c9bf1ae9767623c55251488d297c3f90"}},{"name":"v0.6.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.6.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.6.0","commit":{"sha":"5c7c03c0a137c273c45347d841755bc69e7760c8","url":"https://api.github.com/repos/apex/apex/commits/5c7c03c0a137c273c45347d841755bc69e7760c8"}},{"name":"v0.5.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.5.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.5.1","commit":{"sha":"d48f523fc353892c57048bbbc7c5da5b0372bb38","url":"https://api.github.com/repos/apex/apex/commits/d48f523fc353892c57048bbbc7c5da5b0372bb38"}},{"name":"v0.5.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.5.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.5.0","commit":{"sha":"7abebdc8d45051fb551652366207ca6e9dd50d0f","url":"https://api.github.com/repos/apex/apex/commits/7abebdc8d45051fb551652366207ca6e9dd50d0f"}},{"name":"v0.4.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.4.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.4.1","commit":{"sha":"a9f85e6a150c42017fcc1d9fd4253c954dd40138","url":"https://api.github.com/repos/apex/apex/commits/a9f85e6a150c42017fcc1d9fd4253c954dd40138"}},{"name":"v0.4.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.4.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.4.0","commit":{"sha":"8106abc2a04f0673bed5aaae86c8ed24b59d057d","url":"https://api.github.com/repos/apex/apex/commits/8106abc2a04f0673bed5aaae86c8ed24b59d057d"}},{"name":"v0.3.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.3.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.3.0","commit":{"sha":"5c5a85234131daca776d00582d7b97ed91db9874","url":"https://api.github.com/repos/apex/apex/commits/5c5a85234131daca776d00582d7b97ed91db9874"}},{"name":"v0.2.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.2.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.2.0","commit":{"sha":"eac51ab6d47bcde0a0e0c3d7269f495b07ac058c","url":"https://api.github.com/repos/apex/apex/commits/eac51ab6d47bcde0a0e0c3d7269f495b07ac058c"}},{"name":"v0.1.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.1.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.1.0","commit":{"sha":"b9578e29c97f9eadee4960b032954a039a412b9b","url":"https://api.github.com/repos/apex/apex/commits/b9578e29c97f9eadee4960b032954a039a412b9b"}},{"name":"v0.0.2","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.0.2","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.0.2","commit":{"sha":"b614044f5148082cf48a72d75ef182f478fad17c","url":"https://api.github.com/repos/apex/apex/commits/b614044f5148082cf48a72d75ef182f478fad17c"}},{"name":"v0.0.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.0.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.0.1","commit":{"sha":"ea3a2cfbc0d7704cd76589ad59c15729e852d303","url":"https://api.github.com/repos/apex/apex/commits/ea3a2cfbc0d7704cd76589ad59c15729e852d303"}}]
```

@fibo I'm pretty sure it's the recent one.

**Comment by mthenw** [comment]
Maybe it's a problem with different behaviour of `grep`,  `head`, `sed` or `cut` on different OSes. My results:

1. `curl -s https://api.github.com/repos/apex/apex/tags | grep name`
```
    "name": "v0.7.2",
    "name": "v0.7.1",
    "name": "v0.7.0",
    "name": "v0.6.1",
    "name": "v0.6.0",
    "name": "v0.5.1",
    "name": "v0.5.0",
    "name": "v0.4.1",
    "name": "v0.4.0",
    "name": "v0.3.0",
    "name": "v0.2.0",
    "name": "v0.1.0",
    "name": "v0.0.2",
    "name": "v0.0.1",
```

2. `curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1`
```
    "name": "v0.7.2",
```

3. `curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g'`
```
name:v0.7.2
```

4. `curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2`
```
v0.7.2
```
 
Could you paste yours?

**Comment by elizar** [comment]
@mthenw 

Here it is:
```
% curl -s https://api.github.com/repos/apex/apex/tags | grep name | head -n 1 | sed 's/[," ]//g' | cut -d ':' -f 2
v0.7.2zipball_url
```

**Comment by elizar** [comment]
Not really sure what's causing that weird behaviour

**Comment by mthenw** [comment]
yeah, but could you pase each step separately? Which OS are you running?

**Comment by elizar** [comment]
Hmm... I think this is what's causing it. 

Totally different results than yours

```
% curl -s https://api.github.com/repos/apex/apex/tags | grep name

[{"name":"v0.7.2","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.7.2","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.7.2","commit":{"sha":"96c66ef9da1cf99c39cb1947ed2bb5f567b4db79","url":"https://api.github.com/repos/apex/apex/commits/96c66ef9da1cf99c39cb1947ed2bb5f567b4db79"}},{"name":"v0.7.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.7.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.7.1","commit":{"sha":"315cdeaee9ae93f83353c9f2b3e9c94e93086833","url":"https://api.github.com/repos/apex/apex/commits/315cdeaee9ae93f83353c9f2b3e9c94e93086833"}},{"name":"v0.7.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.7.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.7.0","commit":{"sha":"324bdcb78ca0709186f9d3013645d76f5c0f4a58","url":"https://api.github.com/repos/apex/apex/commits/324bdcb78ca0709186f9d3013645d76f5c0f4a58"}},{"name":"v0.6.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.6.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.6.1","commit":{"sha":"598a0481c9bf1ae9767623c55251488d297c3f90","url":"https://api.github.com/repos/apex/apex/commits/598a0481c9bf1ae9767623c55251488d297c3f90"}},{"name":"v0.6.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.6.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.6.0","commit":{"sha":"5c7c03c0a137c273c45347d841755bc69e7760c8","url":"https://api.github.com/repos/apex/apex/commits/5c7c03c0a137c273c45347d841755bc69e7760c8"}},{"name":"v0.5.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.5.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.5.1","commit":{"sha":"d48f523fc353892c57048bbbc7c5da5b0372bb38","url":"https://api.github.com/repos/apex/apex/commits/d48f523fc353892c57048bbbc7c5da5b0372bb38"}},{"name":"v0.5.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.5.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.5.0","commit":{"sha":"7abebdc8d45051fb551652366207ca6e9dd50d0f","url":"https://api.github.com/repos/apex/apex/commits/7abebdc8d45051fb551652366207ca6e9dd50d0f"}},{"name":"v0.4.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.4.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.4.1","commit":{"sha":"a9f85e6a150c42017fcc1d9fd4253c954dd40138","url":"https://api.github.com/repos/apex/apex/commits/a9f85e6a150c42017fcc1d9fd4253c954dd40138"}},{"name":"v0.4.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.4.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.4.0","commit":{"sha":"8106abc2a04f0673bed5aaae86c8ed24b59d057d","url":"https://api.github.com/repos/apex/apex/commits/8106abc2a04f0673bed5aaae86c8ed24b59d057d"}},{"name":"v0.3.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.3.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.3.0","commit":{"sha":"5c5a85234131daca776d00582d7b97ed91db9874","url":"https://api.github.com/repos/apex/apex/commits/5c5a85234131daca776d00582d7b97ed91db9874"}},{"name":"v0.2.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.2.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.2.0","commit":{"sha":"eac51ab6d47bcde0a0e0c3d7269f495b07ac058c","url":"https://api.github.com/repos/apex/apex/commits/eac51ab6d47bcde0a0e0c3d7269f495b07ac058c"}},{"name":"v0.1.0","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.1.0","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.1.0","commit":{"sha":"b9578e29c97f9eadee4960b032954a039a412b9b","url":"https://api.github.com/repos/apex/apex/commits/b9578e29c97f9eadee4960b032954a039a412b9b"}},{"name":"v0.0.2","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.0.2","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.0.2","commit":{"sha":"b614044f5148082cf48a72d75ef182f478fad17c","url":"https://api.github.com/repos/apex/apex/commits/b614044f5148082cf48a72d75ef182f478fad17c"}},{"name":"v0.0.1","zipball_url":"https://api.github.com/repos/apex/apex/zipball/v0.0.1","tarball_url":"https://api.github.com/repos/apex/apex/tarball/v0.0.1","commit":{"sha":"ea3a2cfbc0d7704cd76589ad59c15729e852d303","url":"https://api.github.com/repos/apex/apex/commits/ea3a2cfbc0d7704cd76589ad59c15729e852d303"}}]
```

**Comment by mthenw** [comment]
looks like new line signs get trimmed (?)

**Comment by elizar** [comment]
That's weird. I tried curling other json endpoints but it doesn't remove new lines. Only github api endpoints.

Since it's most likely just an isolated issue. I can probably close this PR.

**Comment by mthenw** [comment]
yeah, I think so.

**Pull request closed without merging**
