### PR TITLE
add API Gateway integration example. Closes #339

### LINKED ISSUE #339: API Gateway example via TF
https://github.com/hashicorp/terraform/pull/4295#issue-121938495

### PR DESCRIPTION
**Pull request by mthenw**
Next step could be creating module to simplify that...

### CODE REVIEW

**Comment by tj** [comment]
haha nice! yea definitely could be simpler

**Comment by amccloud** [comment]
@mthenw @tj Should apex or another tool handle api gateway orchestration? Would it be okay to generate a terraform config from a `routes` key to the project.json (or routes.json file).

```json
{
  "name": "with-gateway",
  "routes": {
    "/examples/{exampleId}": {
      "method": "GET",
      "function": "hello"
    }
  }
}
```

**Comment by mthenw** [comment]
@amccloud we are tracking API Gateway support in https://github.com/apex/apex/issues/37. It's pretty complicated right now and we are not sure if we want invest time in that.

**Comment by tj** [comment]
Ditto, in a lot of ways I think the approach AWS took with API Gateway is not a very good one. Writing an API is easy, we just need a way to get it in the Lambda containers, they complicated the wrong thing. I wouldn't mind supporting the swagger stuff just because the import API is so easy now, but I still think API Gateway is a weird solution

**Pull request merged**
